/// Lista de todos los Nano Suits (trajes) disponibles en Stellar Blade
/// extraída de las fuentes [106-119] del PDF proporcionado.
const List<String> stellarBladeOutfits = [
  // Juego base [106-107]
  'Skin Suit',
  'Planet Diving Suit (7th)',
  'Planet Diving Suit (7th) V2',
  'Keyhole Suit',
  'Racer\'s High',
  'Wasteland Adventurer',
  'Planet Diving Suit (6th)',
  'Stargazer Suit',
  'Red Passion',
  'Cyber Magician',
  'Holiday Rabbit',
  'Raven Suit',
  'Black Pearl',
  'Orca Exploration Suit',
  'Moutan Peony',
  'Cybernetic Dress',
  'Keyhole Dress',
  'Sporty Yellow',
  'Junk Mechanic',
  'Daily Denim',
  'Black Full Dress',
  'Daily Biker',
  'Daily Mascot',
  'Daily Force',
  'Daily Knitted Dress',
  'Fluffy Bear',
  'Motivation',
  'Punk Top',
  'Orca Engineer',
  'Black Rose',
  'Photogenic',
  'Prototype Planet Diving Suit',
  'La Vie en Rose',
  'Ocean Maid',
  
  // New Game+ [108]
  'Red Pearl',
  'Angelic Rose',
  'Telegenic',
  'Resonance',
  'Punk Style',
  'Orca Techie',
  'Air Ace',
  'White Monsoon',
  'Planet Diving Suit (3rd) V2',
  'Prototype Planet Diving Suit V2',
  'FourSeconds Biker',
  'Comfort Sailor',
  'FourSeconds Denim',
  'Autonetic Bondage',
  'Wild Wave',
  'Junk Engineer',
  'White Full Dress',
  'Pink Bear',
  'Comfort Mascot',
  'Comfort Force',
  'Wasteland Explorer',
  'Sporty Energy',
  'Comfort Knitted Dress',
  'Crew Style',
  'Cyber Trickster',
  'Orca Pathfinder',
  'Keyhole Dress (NG+)', // Objeto separado del "Keyhole Dress" base
  'Cybernetic Suit',
  'Holiday Bunny',
  'Emerald Passion',
  'Planet Diving Suit (7th) V3',
  'Planet Diving Suit (2nd) V2',
  'Speeder\'s High',
  'Planet Diving Suit (6th) V2',

  // Actualizaciones [109-115]
  'Black Kunoichi',
  'White Kunoichi',
  'Midsummer Redhood',
  'Midsummer Alice',
  'Neurolink Suit',
  'Four Seconds Destroyed Denim',
  'Cyber Illusionist',
  'Wave Diver Bikini',
  'Wave Oblique Monokini',
  'FourSeconds Black Denim',
  'FourSeconds Everyday Wear',
  'Neurolink Skin',
  'War Dress',
  'Santa Dress',
  'Planet Diving Protection Suit (7th)',
  'Planet Diving Protection Suit (7th) V2',
  'Tidal Maid',
  'Planet Diving Suit (6th) V3',
  'Planet Diving Suit (5th)',
  'Sensate Skin',
  'Royal Guard Suit',
  'Prototype Neurolink Suit',
  'Prototype Sensate Suit',
  'War Aegis',
  'FourSeconds Essential Wear',
  'FourSeconds Striped Denim',
  'Office Style',
  'Silver Kunoichi',
  'Shadow Kunoichi',
  'Peony',
  'Hydrangea',
  'Black Lotus',
  'Neurocircuit Bondage',
  'War Suit',
  'Cyber Bunny',
  'White Pearl',
  'Aqua Pearl',
  'Ultimate Bunny',
  'Extreme Bunny',
  'Crimson Wings',
  'Ocean String',

  // DLC/Packs [117-119]
  'Planet Diving Suit (Captain)',
  'YoRHa No.2 Type B Uniform',
  'YoRHa Uniform 1',
  'YoRHa Unofficial Ceremonial Attire',
  'YoRHa Type A No.2 Uniform',
  'Wandering Swordfighter Outfit',
  'Cooling Suit',
  'Elegant Dress',
  'Elysion Combat Uniform',
  'Missing Link',
  'Never Look Back',
];