/// Lista de todos los Nano Suits (trajes) disponibles en Stellar Blade
/// extraída de las fuentes [1-3] del archivo CSV proporcionado.
const List<String> stellarBladeOutfits = [
  // New Game
  'Skin Suit',
  'Planet Diving Suit (7th)',
  'Planet Diving Suit (7th) V2',
  'Keyhole Suit',
  'Raven Suit',
  'Fluffy Bear',
  'Sky Ace',
  'Black Rose',
  'La Vie en Rose',
  'Blue Monsoon',
  'Black Pearl',
  'Ocean Maid',
  'Planet Diving Suit (6th)',
  'Planet Diving Suit (3rd)',
  'Prototype Planet Diving Suit',
  'Planet Diving Suit (2nd)',
  'Photogenic',
  'Daily Mascot',
  'Daily Force',
  'Daily Biker',
  'Daily Sailor',
  'Daily Denim',
  'Moutan Peony',
  'Cybernetic Bondage',
  'Racer\'s High',
  'Holiday Rabbit',
  'Black Wave',
  'Cyber Magician',
  'Cybernetic Dress',
  'Motivation',
  'Punk Top',
  'Orca Exploration Suit',
  'Orca Engineer',
  'Wasteland Adventurer',
  'Red Passion',
  'Sporty Yellow',
  'Junk Mechanic',
  'Black Full Dress',
  'Daily Knitted Dress',

  // New Game +
  'Red Pearl',
  'Angelic Rose',
  'Telegenic',
  'Resonance',
  'Punk Style',
  'Orca Techie',
  'Air Ace',
  'White Monsoon',
  'Planet Diving Suit (3rd) V2',
  'Prototype Planet Diving Suit V2',
  'FourSeconds Biker',
  'Comfort Sailor',
  'FourSeconds Denim',
  'Autonetic Bondage',
  'Wild Wave',
  'Junk Engineer',
  'White Full Dress',
  'Pink Bear',
  'Comfort Mascot',
  'Comfort Force',
  'Wasteland Explorer',
  'Sporty Energy',
  'Comfort Knitted Dress',
  'Crew Style',
  'Cyber Trickster',
  'Orca Pathfinder',
  'Keyhole Dress',
  'Cybernetic Suit',
  'Holiday Bunny',
  'Emerald Passion',
  'Planet Diving Suit (7th) V3',
  'Planet Diving Suit (2nd) V2',
  'Speeder\'s High',
  'Planet Diving Suit (6th) V2',

  // Update 1.003
  'Black Kunoichi',
  'White Kunoichi',
  'Midsummer Redhood',
  'Midsummer Alice',
  'Neurolink Suit',

  // Update 1.004
  'FourSeconds Destroyed Denim',
  'Cyber Illusionist',

  // Update 1.006
  'Wave Diver Bikini',
  'Wave Oblique Monokini',

  // Update 1.009
  'FourSeconds Black Denim',
  'FourSeconds Everyday Wear',
  'Neurolink Skin',
  'War Dress',

  // Update 1.010
  'Santa Dress',

  // Update 1.011
  'Planet Diving Protection Suit (7th)',
  'Planet Diving Protection Suit (7th) V2',
  'Tidal Maid',
  'Planet Diving Suit (6th) V3',
  'Planet Diving Suit (5th)',
  'Sensate Skin',
  'Royal Guard Suit',
  'Prototype Neurolink Suit',
  'Prototype Sensate Suit',
  'War Aegis',
  'FourSeconds Essential Wear',
  'FourSeconds Striped Denim',
  'Office Style',
  'Silver Kunoichi',
  'Shadow Kunoichi',
  'Peony',
  'Hydrangea',
  'Black Lotus',
  'Neurocircuit Bondage',
  'War Suit',
  'Cyber Bunny',
  'White Pearl',
  'Aqua Pearl',
  'Ultimate Bunny',
  'Extreme Bunny',
  'Crimson Wings',

  // Update 1.014
  'Ocean String',

  // Deluxe Pack
  'Stargazer Suit',

  // Tachyon Pack
  'Planet Diving Suit (Captain)',

  // NieR:Automata DLC
  'YoRHa No.2 Type B Uniform',
  'YoRHa Uniform 1',
  'YoRHa Unofficial Ceremonial Attire',
  'YoRHa Type A No.2 Uniform',

  // Goddess of Victory: NIKKE DLC
  'Wandering Swordfighter Outfit',
  'Cooling Suit',
  'Elegant Dress',
  'Elysion Combat Uniform',
  'Missing Link',
  'Never Look Back',
];